export {Home} from "./Home/Home";
export {Notes} from "./Notes/Notes";
export {Archive} from "./Archive/Archive";
export {Trash} from "./Trash/Trash";
export {Login} from "./Auth/Login";
export {SignUp} from "./Auth/SignUp";
export {Label} from "./Label/Label";
export {Profile} from "./Profile/Profile";
export {PageNotFound} from "./404/PageNotFound";
