export const USER_ACTIONS = {
  INITIAL_NOTES: "INITIAL_NOTES",
  ADD_NEW_NOTE: "ADD_NEW_NOTE",
  EDIT_NOTE: "EDIT_NOTE",
  ADD_TO_ARCHIVE: "ADD_TO_ARCHIVE",
  RESTORE_FROM_ARCHIVE: "RESTORE_FROM_ARCHIVE",
  ADD_TO_TRASH: "ADD_TO_TRASH",
  RESTORE_FROM_TRASH: "RESTORE_FROM_TRASH",
  DELETE_FROM_TRASH: "DELETE_FROM_TRASH",
};
